- name: Load benchmark arguments
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ arguments | dict2items }}"

- name: Start Infinispan server
  ansible.builtin.include_role:
    name: server
  vars:
    operation: run,create_cache

- name: Run Hyperfoil agent
  ansible.builtin.include_role:
    name: hyperfoil_agent
    apply:
      delegate_to: "{{ groups['hyperfoil_agent'][0] }}"
  run_once: true
  vars:
    operation: run
    hyperfoil_run_description: "{{ server_image }}-{{ cache_file }}"

- name: Shutdown Infinispan server
  ansible.builtin.include_role:
    name: server
  vars:
    operation: delete_cache,shutdown
